const page = document.body.dataset.page || 'home';
const nav = `<a class="brand" href="index.html" aria-label="Together home"><img src="favicon.svg" alt="" width="34" height="34">together</a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu</button><nav class="navlinks" id="site-nav" aria-label="Main navigation"><a href="explore.html" ${page==='explore'?'aria-current="page"':''}>Find a circle</a><a href="how-it-works.html" ${page==='how'?'aria-current="page"':''}>How it works</a><a href="pricing.html" ${page==='pricing'?'aria-current="page"':''}>Membership</a><a class="button small" href="app.html">Try the preview</a></nav>`;
document.querySelector('[data-header]').innerHTML=nav;
document.querySelector('[data-footer]').innerHTML=`<footer class="footer"><div><a class="brand" href="index.html">together</a><p>For the books you’ve been meaning to finish.<br>And the people you haven’t met yet.</p></div><div class="footer-links"><a href="explore.html">Find a circle</a><a href="how-it-works.html">How it works</a><a href="pricing.html">Membership</a><a href="community.html">Community & safety</a><a href="privacy.html">Privacy</a></div></footer><div class="copyright">Together · Product preview · No live circles, accounts, or subscriptions yet.</div>`;
const menu=document.querySelector('.menu-button');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));document.querySelector('.navlinks').classList.toggle('open',open)});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const filter=button.dataset.filter;document.querySelectorAll('[data-format]').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.format!==filter});document.querySelector('[data-count]').textContent=filter==='all'?'2 sample circles · both ways to belong':'1 sample circle · preview only';}));

const initialFilter=new URLSearchParams(location.search).get("format");
if(initialFilter){[...document.querySelectorAll("[data-filter]")].find(button=>button.dataset.filter===initialFilter)?.click();}
