import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const u=i=>`00000000-0000-0000-0000-${String(i).padStart(12,'0')}`;
test('PostgreSQL schema compiles and enforces membership, RLS, privacy, entitlements, capacity',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.jwt() returns jsonb language sql stable as $$select '{}'::jsonb$$;
 grant usage on schema auth to anon,authenticated; grant execute on all functions in schema auth to anon,authenticated;`);
 await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 await db.query(`insert into auth.users values ($1),($2),($3),($4)`,[u(1),u(2),u(3),u(4)]);
 await db.query(`insert into together.books(id,title,author,chapters,published) values($1,'Test book','Test author',10,true)`,[u(10)]);
 await db.query(`insert into together.circles(id,book_id,name,mode,status,capacity) values($1,$3,'One','virtual','open',2),($2,$3,'Two','virtual','open',2)`,[u(20),u(21),u(10)]);
 const as=async id=>{await db.exec('reset role');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[id||'']);await db.exec(`set role ${id?'authenticated':'anon'}`);};
 const cmd=(action,payload={})=>db.query(`select together.command($1,$2::jsonb) as result`,[action,JSON.stringify(payload)]);
 await as(null);
 assert.equal((await db.query('select * from together.books')).rows.length,1);
 await assert.rejects(db.query('select * from together.profiles'),/permission denied/);
 await assert.rejects(cmd('join',{circle_id:u(20)}),/permission denied/);
 for(let i=1;i<=4;i++){await as(u(i));await cmd('save_profile',{pseudonym:`Reader ${i}`});}
 await as(u(1));await cmd('join',{circle_id:u(20)});await cmd('join',{circle_id:u(20)});
 await assert.rejects(cmd('join',{circle_id:u(21)}),/one active circle/);
 await assert.rejects(cmd('create_circle',{book_id:u(10),name:'Unauthorized',mode:'virtual'}),/Plus entitlement/);
 await assert.rejects(db.query(`insert into together.memberships values ($1,$2,now())`,[u(21),u(1)]),/permission denied/);
 await cmd('post',{circle_id:u(20),chapter:1,body:'A real test post'});
 await assert.rejects(cmd('post',{circle_id:u(20),chapter:11,body:'Invalid'}),/Invalid chapter/);
 await cmd('progress',{circle_id:u(20),chapter:10});
 assert.equal((await db.query('select * from together.badges')).rows.length,2);
 await as(u(2));await cmd('join',{circle_id:u(20)});
 assert.equal((await db.query('select * from together.posts')).rows.length,1);
 assert.equal((await db.query('select * from together.profiles')).rows.length,2);
 assert.equal((await db.query('select * from together.progress')).rows.length,0);
 const post=(await db.query('select id from together.posts')).rows[0].id;
 await cmd('report',{post_id:post,reason:'Please review this test'});
 await assert.rejects(db.query('select * from together_private.reports'),/permission denied/);
 await cmd('block',{user_id:u(1)});
 assert.equal((await db.query('select * from together.posts')).rows.length,0);
 assert.equal((await db.query('select * from together.profiles')).rows.length,1);
 await as(u(3));
 await assert.rejects(cmd('join',{circle_id:u(20)}),/full/);
 assert.equal((await db.query('select * from together.posts')).rows.length,0);
 assert.equal((await db.query('select * from together.profiles')).rows.length,1);
 await assert.rejects(cmd('post',{circle_id:u(20),chapter:1,body:'Intrusion'}),/membership required/);
 await assert.rejects(cmd('report',{post_id:post,reason:'Unauthorized report'}),/unavailable/);
 await assert.rejects(db.query(`update together.profiles set pseudonym='Hijacked' where id=$1`,[u(1)]),/permission denied/);
 await db.exec('reset role');
 await db.query(`insert into together_private.entitlements values ($1,now()+interval '1 day','admin')`,[u(3)]);
 await as(u(3));await cmd('join',{circle_id:u(21)});
 await cmd('create_circle',{book_id:u(10),name:'An approved Plus draft',mode:'virtual'});
 await assert.rejects(cmd('create_circle',{book_id:u(10),name:'Second owned circle',mode:'virtual'}),/One owned active/);
 await as(u(1));await cmd('leave',{circle_id:u(20)});
 assert.equal((await db.query('select * from together.posts')).rows.length,0);
 await cmd('join',{circle_id:u(21)});
 await as(u(4));await assert.rejects(cmd('join',{circle_id:u(21)}),/full/);
 await db.exec('reset role');
 const unsafe=(await db.query(`select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('together','together_private') and c.relkind='r' and not c.relrowsecurity`)).rows;
 assert.deepEqual(unsafe,[]);
 } finally {await db.close();}
});
